### PR TITLE
Embedded Interceptors: Providing Traceability for REST Proxy, Connect and KSQL

### PR DESCRIPTION
**Pull request by riferrei**
The interceptors provided by the Java Client package need that the developer instantiates a Tracer and make it available in the JVM via the GlobalTracer utility class. This works well when the developer has access to the source code and more importantly, has access to change it.

However, there are Kafka tools out there that don't allow the modification of the code and the only way to add new behavior is by registering interceptors. These interceptors would need to instantiate their own tracers so they could send the traces elsewhere.

The Embedded Interceptors allow that, and they are a nice add-on for the OpenTracing project. Many developers make use of tools like **REST Proxy**, **Kafka Connect**, and **KSQL**, and these tools don't allow any customization of their code other than executing custom interceptors.

### CODE REVIEW

**Comment by malafeev** [comment]
@riferrei you added dependency on the jaeger tracer.
I don't think it's acceptable.
Library should not depend on any opentracing implementation.

**Comment by riferrei** [comment]
Hi @malafeev,

I understand your concern. I am happy to remove the dependency but I couldn't find any example where I can create a Jaeger tracer using the OpenTracing API. Is there any example that I can follow?

Unfortunately the whole purpose of this PR is allowing these interceptors to instantiate their own tracers, and presumably, I can only do it using the client libraries.

**Comment by malafeev** [comment]
@riferrei 
If it's not possible to use `GlobalTracer` then I propose to use TracerResolver.
API: https://github.com/opentracing-contrib/java-tracerresolver
Jaeger implementation: https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-tracerresolver

So idea that library will have TracerResolver API dependency only.
But when you start app you also provide Jaeger Tracer Resolver jar which will instantiate Jaeger Tracer.

**Comment by malafeev** [comment]
@yurishkuro please correct me if I'm wrong. But looks like TracerResolver is only option.

**Comment by riferrei** [comment]
I am going to work in a generic way to make this implementation, so the promises of the project are not compromised. Perhaps it was immature proposing a PR at this stage. Eventually, I may file another PR with the changes.

**Comment by yurishkuro** [comment]
> @yurishkuro please correct me if I'm wrong. But looks like TracerResolver is only option.

I don't think this library should ever be in charge of instantiating the tracer, it should be done by the application or the app framework. My standard recommendation for client libraries is to accept tracer explicitly as an argument, with a possible fallback on the global tracer if absolutely necessary.

**Pull request closed without merging**
