### PR TITLE
Override additional methods in TracingProducerFactory to avoid Unsupp…

### PR DESCRIPTION
**Pull request by RuslanHryn**
Currently, TracingProducerFactory is not implementing all methods from  ProducerFactory. Therefore, if use an unimplemented method then you may get UnsupportedOperationException
I've implemented all method to fix this issue

### CODE REVIEW

**Comment by hpuac** [comment]
Hey @RuslanHryn and @malafeev, thx for fixing this! It's exactly the issue we currently run into when updating the tracing dependencies. When can we expect to get a new tag? :slightly_smiling_face:

**Comment by JonathanHel** [comment]
Any updates for a new release? We definitly need this! @RuslanHryn  @malafeev

**Comment by aadamovi** [comment]
hi, I have a similar issue. was this fix released? if so what is the version? thx

**Comment by unv-unv** [comment]
Still no release with this fix available in https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-kafka-spring

**Pull request merged**
